# Generated by Django 4.2.5 on 2023-10-04 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_plants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plants',
            name='NativeArea',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
